version: "3"
services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/usr/src/app
    command: bash -c 'npm i && npm run dev'
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes: 
  mongo: