version: "3"
services:
  app:
    container_name: app
    build: .
    volumes:
      - ./dist:/usr/src/app
    command: sh -c 'npm i && npm start'
    ports:
      - "3050:3050"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes: 
  mongo: